---
- name: Remove useless packages
  yum:
    name: "{{ remove_distribution_specific_packages }}"
    state: absent
  when: remove_distribution_specific_packages is defined
  tags:
    - packages

- name: Upgrade packages
  yum:
    name: '*'
    state: latest
  tags:
    - packages

- name: Add nice prompt for root user
  blockinfile:
    dest: /root/.bashrc
    block: |
      ps1_prompt() {
          local ps1_exit=$?

          if [ $ps1_exit -eq 0 ]; then
              ps1_status='\$'
          else
              ps1_status=`echo -e "\[\\033[1;31m\]"'\\\$'"\[\\033[00m\]"`
          fi

          PS1="\[\\033[01;31m\]\u@\h\[\\033[00m\]:\[\\033[01;34m\]\w${ps1_status} \[\\033[00m\]"
      }

      PROMPT_COMMAND="ps1_prompt;$PROMPT_COMMAND"
    backup: yes
  tags:
    - bashrc

- name: Tweak auditlog pre-prepare audit all commands run in the system
  blockinfile:
    dest: /etc/audit/rules.d/audit.rules
    block: |
      # Log all executed commands
      #-a exit,always -F arch=b64 -F euid=0 -S execve -k root-commands
      #-a exit,always -F arch=b32 -F euid=0 -S execve -k root-commands
  tags:
    - audit

- name: Disable selinux
  selinux:
    state: disabled
  tags:
    - selinux

- name: Check the presence of /etc/default/grub
  stat:
    path: /etc/default/grub
  register: grub_default
  tags:
    - grub

- name: Modify grub settings
  replace:
    dest: /etc/default/grub
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    mode: u=rw,g=r,o=r
  loop:
    - regexp: '^GRUB_TIMEOUT=.*'
      replace: 'GRUB_TIMEOUT=1'
    - regexp: 'nofb quiet splash=quiet'
      replace: 'nofb quiet rootflags=usrquota,grpquota vmwgfx.enable_fbdev=0 verbose consoleblank=0 no_timer_check splash=quiet'
  notify: generate grub configuration
  when: grub_default.stat.exists
  tags:
    - grub

- name: Change HW Clock configuration
  replace:
    dest: /etc/sysconfig/ntpdate
    regexp: 'SYNC_HWCLOCK=no'
    replace: 'SYNC_HWCLOCK=yes'
    backup: yes
    mode: u=rw,g=r,o=r
  tags:
    - ntp

- name: Set NTP step stickers
  template:
    src: etc/ntp/step-tickers.j2
    dest: /etc/ntp/step-tickers
    backup: yes
    mode: u=rw,g=r,o=r
  tags:
    - ntp

- name: Chnage /etc/yum/yum-cron.conf
  block:
    - name: Configure yum-cron
      replace:
        path: /etc/yum/yum-cron.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
        mode: u=rw,g=r,o=r
      loop:
        - regexp: '^apply_updates.*'
          replace: 'apply_updates = yes'
      tags:
        - yum-cron

    - name: Configure yum-cron
      replace:
        dest: /etc/yum/yum-cron-hourly.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
        mode: u=rw,g=r,o=r
      loop:
        - regexp: '^update_cmd.*'
          replace: 'update_cmd = security-severity:Critical'
        - regexp: '^apply_updates.*'
          replace: 'apply_updates = yes'
        - regexp: '^update_messages.*'
          replace: 'update_messages = yes'
        - regexp: '^download_updates.*'
          replace: 'download_updates = yes'
      tags:
        - yum-cron
  when: ansible_distribution_major_version|int > 6

- name: Add /usr/local/bin/etc_issue.sh script
  template:
    src: usr/local/bin/etc_issue.sh.j2
    dest: /usr/local/bin/etc_issue.sh
    mode: 0755
  tags:
    - issue

- name: Create link /usr/local/bin/etc_issue.sh /etc/profile.d/etc_issue.sh
  file:
    src: /usr/local/bin/etc_issue.sh
    dest: /etc/profile.d/etc_issue.sh
    state: link
  tags:
    - issue

# https://access.redhat.com/solutions/1564823
- name: Prevent systemd to log too many messages like "Starting Session 1398 of user root."
  copy:
    src: etc/rsyslog.d/ignore-systemd-session-slice.conf
    dest: /etc/rsyslog.d/ignore-systemd-session-slice.conf
    mode: u=rw,g=r,o=r
  tags:
    - syslog
